spring.datasource.url=jdbc:mysql://localhost:3306/tacocloud?useSSL=true&requireSSL=true&verifyServerCertificate=true&trustCertificateKeyStoreUrl=classpath:truststore.jks&trustCertificateKeyStorePassword=changeit
spring.datasource.username=root
spring.datasource.password=psa_db_password

spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.prefix=classpath:/web/templates/
spring.web.resources.static-locations=classpath:/web/static/