package web.persistence.models;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import com.fasterxml.jackson.databind.ObjectMapper;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * JPA Entity for storing poker hand games in the database.
 * This is SEPARATE from pokerlibrary.models.Game (domain model).
 * Stores the full game as JSON for flexibility and easy serialization.
 */
@Entity
@Table(name = "games",
        indexes = {
                @Index(name = "idx_user_id", columnList = "user_id"),
                @Index(name = "idx_game_id", columnList = "game_id"),
                @Index(name = "idx_date_created", columnList = "date_created")
        })
@Data
@NoArgsConstructor
@AllArgsConstructor
public class GameEntity {

    /**
     * Primary key - auto-generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User who owns this game (many-to-one relationship)
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, foreignKey = @ForeignKey(name = "fk_games_user"))
    private UserEntity user;

    /**
     * Unique game ID from poker hand (e.g., "HD1517789305")
     */
    @Column(name = "game_id", nullable = false, length = 50)
    private String gameId;

    /**
     * Full game data stored as JSON
     * Contains all streets, players, actions, cards, etc.
     */
    @Column(name = "game_data", columnDefinition = "JSON", nullable = false, length = 50000)
    private String gameData;

    /**
     * When the poker hand was played (from hand history)
     */
    @Column(name = "date_played")
    private LocalDateTime datePlayed;

    /**
     * Pot type classification (unraised, single raised, 3bet, 4bet, 5+ bet)
     */
    @Column(name = "pot_type", length = 20)
    private String potType;

    /**
     * Hero's win/loss amount for this hand
     * ✅ CHANGED: BigDecimal for precise monetary values
     */
    @Column(name = "hero_winloss", precision = 10, scale = 2)
    private BigDecimal heroWinloss;

    /**
     * Final pot size at end of hand
     * ✅ CHANGED: BigDecimal for precise monetary values
     */
    @Column(name = "final_pot", precision = 10, scale = 2)
    private BigDecimal finalPot;

    /**
     * When this record was created in database
     */
    @Column(name = "date_created", nullable = false, updatable = false)
    private LocalDateTime dateCreated;

    /**
     * When this record was last updated
     */
    @Column(name = "date_updated")
    private LocalDateTime dateUpdated;

    /**
     * Automatically set dateCreated before persisting
     */
    @PrePersist
    protected void onCreate() {
        dateCreated = LocalDateTime.now();
        dateUpdated = LocalDateTime.now();
    }

    /**
     * Automatically update dateUpdated before updating
     */
    @PreUpdate
    protected void onUpdate() {
        dateUpdated = LocalDateTime.now();
    }

    /**
     * Convert domain Game model to Entity
     * @param game domain model from pokerlibrary.models
     * @param user owner of this game
     * @return GameEntity ready to save to database
     */
    public static GameEntity fromDomainGame(pokerlibrary.models.Game game, UserEntity user) {
        GameEntity entity = new GameEntity();
        entity.setUser(user);
        entity.setGameId(game.getGameId());
        entity.setDatePlayed(game.getDate() != null ?
                LocalDateTime.ofInstant(game.getDate().toInstant(), java.time.ZoneId.systemDefault()) : null);

        // ✅ Convert double to BigDecimal for precise monetary values
        entity.setHeroWinloss(BigDecimal.valueOf(game.getHeroWinloss()));
        entity.setFinalPot(BigDecimal.valueOf(game.getFinalPot()));

        // Convert entire game to JSON for storage
        try {
            ObjectMapper mapper = new ObjectMapper();
            entity.setGameData(mapper.writeValueAsString(game));
        } catch (Exception e) {
            throw new RuntimeException("Failed to serialize game to JSON", e);
        }

        return entity;
    }

    /**
     * Convert Entity back to domain Game model
     * @return domain model from pokerlibrary.models
     */
    public pokerlibrary.models.Game toDomainGame() {
        try {
            ObjectMapper mapper = new ObjectMapper();
            return mapper.readValue(gameData, pokerlibrary.models.Game.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to deserialize game from JSON", e);
        }
    }

    /**
     * Set pot type (with validation)
     * @param potType one of: unraised, single raised, 3bet, 4bet, 5+ bet, undefined
     */
    public void setPotType(String potType) {
        if (potType != null && !potType.matches("^(unraised|single raised|3bet|4bet|5\\+ bet|undefined)$")) {
            throw new IllegalArgumentException("Invalid pot type: " + potType);
        }
        this.potType = potType;
    }
}